language: ruby

# ensure stuff is installed we can use to test
before_install:
  - which helm
  - which kubectl

script:
  - helm lint ./helm
  - helm template test ./helm


after_success:
  - echo "This chart passes linting and templating"
