# https://raw.githubusercontent.com/IBM/t8c-operator/main/deploy/role_binding.yaml
#
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: t8c-operator
subjects:
  - kind: ServiceAccount
    name: t8c-operator
roleRef:
  kind: Role
  name: t8c-operator
  apiGroup: rbac.authorization.k8s.io
